apiVersion: v1
kind: Service
metadata:
  name: static-service-dev
  namespace: development
  labels:
    app.kubernetes.io/name: static-files
    app.kubernetes.io/instance: static-files-asdfgh
    app.kubernetes.io/version: "v2"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: workout-app
    env: development
spec:
  selector:
    app: static-files-dev
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: s-files-port
    protocol: TCP
