apiVersion: elasticsearch.k8s.elastic.co/v1 
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: elasticsearch-abcxyz
    app.kubernetes.io/version: "v8.13.4"
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: logging
spec:
  version: 8.13.4
  nodeSets:
  - name: default
    config:
      node.roles: ["master", "data", "ingest", "ml", "remote_cluster_client"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
    count: 1