apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
  namespace: logging
  labels:
    app.kubernetes.io/name: logstash
    app.kubernetes.io/instance: logstash-abcxyz
    app.kubernetes.io/version: "v8.13.4"
    app.kubernetes.io/component: log-ingest
    app.kubernetes.io/part-of: logging
spec:
  count: 1
  elasticsearchRefs:
    - name: elasticsearch
      clusterName: eck
      namespace: logging
  version: 8.13.4
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }

        filter {
          json {
            source => message
            target => log_data
          }
        }

        output {
          elasticsearch {
            hosts => [ "${ECK_ES_HOSTS}" ]
            ssl_certificate_authorities => "${ECK_ES_SSL_CERTIFICATE_AUTHORITY}"
            user => "${ECK_ES_USER}"
            password => "${ECK_ES_PASSWORD}"
          }
        }
  services:
    - name: beats
      service:
        spec:
          type: NodePort
          ports:
            - port: 5044
              # name: "filebeat"
              protocol: TCP
              targetPort: 5044