ARG GO_VERSION=1.22.2

# Stage 1 - build the application
FROM golang:${GO_VERSION}-alpine as build
RUN apk add --no-cache git

# Copy deps
WORKDIR /src
COPY ./go.mod ./go.sum ./
RUN go mod download

# Copy code
COPY ./ ./

# Tests
RUN CGO_ENABLED=0 go test -timeout 30s ./...

# Build the binary
RUN CGO_ENABLED=0 go build \
    -installsuffix 'static' \
    -o /app ./cmd/app

# Stage 2 - build container to run
FROM scratch AS final

# Get the binary from the build step
COPY --from=build /app /app

ENTRYPOINT [ "/app" ]
