apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-files-dev
spec:
  selector:
    matchLabels:
      app: static-files-dev
  template:
    metadata:
      labels:
        app: static-files-dev
    spec:
      containers:
      - name: static-files-dev
        image: behlers22/wa-static-files:latest
        resources:
          limits:
            memory: "8Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: s-files-port
