apiVersion: v1
kind: Service
metadata:
  name: static-service-dev
spec:
  selector:
    app: static-files-dev
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: s-files-port
    protocol: TCP
