apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-dev
  namespace: development
  labels:
    app.kubernetes.io/name: web-server
    app.kubernetes.io/instance: web-server-asdfgh
    app.kubernetes.io/version: "v0.0.1"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: workout-app
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-dev
  template:
    metadata:
      namespace: development
      labels:
        app: webserver-dev
        app.kubernetes.io/name: web-server
        app.kubernetes.io/instance: web-server-asdfgh
        app.kubernetes.io/version: "v0.0.1"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: workout-app
        role: replica
        env: development
    spec:
      containers:
      - name: webserver-dev
        image: behlers22/wa-web-server:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http-web-svc
        command: 
        - "/app"
        envFrom:
        - configMapRef:
            name: webserver-dev
      
