apiVersion: v1
kind: Service
metadata:
  name: webserver-service-dev
  namespace: development
  labels:
    app.kubernetes.io/name: web-server
    app.kubernetes.io/instance: web-server-asdfgh
    app.kubernetes.io/version: "v0.0.1"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: workout-app
    env: development
spec:
  selector:
    app: webserver-dev
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-web-svc
    protocol: TCP
    # name: ws-port
