apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: namespace-asdfgh
    app.kubernetes.io/part-of: workout-app