apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  namespace: development
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/instance: ingress-asdfgh
    app.kubernetes.io/version: "v0.0.1"
    app.kubernetes.io/component: networking
    app.kubernetes.io/part-of: workout-app
    env: development
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: INGRESSCOOKIE
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/session-cookie-path: "/api"
    nginx.ingress.kubernetes.io/session-cookie-samesite: Strict
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET"
    nginx.ingress.kubernetes.io/limit-rps: "25"
    nginx.ingress.kubernetes.io/limit-connections: "20"
    nginx.ingress.kubernetes.io/limit-rate: "128k"
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /()(.*)
        backend:
          service:
            name: static-service-dev
            port:
              number: 80
      - pathType: ImplementationSpecific
        path: /api(/|$)(.*)
        backend:
          service:
            name: webserver-service-dev
            port: 
              number: 80 
