apiVersion: v1
kind: ConfigMap
metadata:
  name: workout-service
  namespace: development
  labels:
    app.kubernetes.io/name: workout-service
    app.kubernetes.io/instance: workout-service-asdfgh
    app.kubernetes.io/version: "v0.0.1"
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: workout-app
    env: development
data:
  ENVIRONMENT: development
  PORT: ":8080"
