apiVersion: v1
kind: Service
metadata:
  name: workout-service
  namespace: development
  labels:
    app.kubernetes.io/name: workout-serivce
    app.kubernetes.io/instance: workout-service-asdfgh
    app.kubernetes.io/version: "v0.0.1"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: workout-app
    env: development
spec:
  selector:
    app: workout-serivce
    env: development
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: workout-service-port
    protocol: TCP
